namespace PerfTap.Interop
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	internal static class PdhResults
	{
		public const long PDH_ACCESS_DENIED = 0xc0000bdbL;
		public const long PDH_ASYNC_QUERY_TIMEOUT = 0x800007dbL;
		public const long PDH_BINARY_LOG_CORRUPT = 0xc0000bf7L;
		public const long PDH_CALC_NEGATIVE_DENOMINATOR = 0x800007d6L;
		public const long PDH_CALC_NEGATIVE_TIMEBASE = 0x800007d7L;
		public const long PDH_CALC_NEGATIVE_VALUE = 0x800007d8L;
		public const long PDH_CANNOT_CONNECT_MACHINE = 0xc0000bc3L;
		public const long PDH_CANNOT_CONNECT_WMI_SERVER = 0xc0000be8L;
		public const long PDH_CANNOT_READ_NAME_STRINGS = 0xc0000bc8L;
		public const long PDH_CANNOT_SET_DEFAULT_REALTIME_DATASOURCE = 0x800007dcL;
		public const long PDH_COUNTER_ALREADY_IN_QUERY = 0xc0000bf6L;
		public const long PDH_CSTATUS_BAD_COUNTERNAME = 0xc0000bc0L;
		public const long PDH_CSTATUS_INVALID_DATA = 0xc0000bbaL;
		public const long PDH_CSTATUS_ITEM_NOT_VALIDATED = 0x800007d3L;
		public const long PDH_CSTATUS_NEW_DATA = 1L;
		public const long PDH_CSTATUS_NO_COUNTER = 0xc0000bb9L;
		public const long PDH_CSTATUS_NO_COUNTERNAME = 0xc0000bbfL;
		public const long PDH_CSTATUS_NO_INSTANCE = 0x800007d1L;
		public const long PDH_CSTATUS_NO_MACHINE = 0x800007d0L;
		public const long PDH_CSTATUS_NO_OBJECT = 0xc0000bb8L;
		public const long PDH_CSTATUS_VALID_DATA = 0L;
		public const long PDH_DATA_SOURCE_IS_LOG_FILE = 0xc0000bceL;
		public const long PDH_DATA_SOURCE_IS_REAL_TIME = 0xc0000bcfL;
		public const long PDH_DIALOG_CANCELLED = 0x800007d9L;
		public const long PDH_END_OF_LOG_FILE = 0x800007daL;
		public const long PDH_ENTRY_NOT_IN_LOG_FILE = 0xc0000bcdL;
		public const long PDH_FILE_ALREADY_EXISTS = 0xc0000bd2L;
		public const long PDH_FILE_NOT_FOUND = 0xc0000bd1L;
		public const long PDH_FUNCTION_NOT_FOUND = 0xc0000bbeL;
		public const long PDH_INCORRECT_APPEND_TIME = 0xc0000bfbL;
		public const long PDH_INSUFFICIENT_BUFFER = 0xc0000bc2L;
		public const long PDH_INVALID_ARGUMENT = 0xc0000bbdL;
		public const long PDH_INVALID_BUFFER = 0xc0000bc1L;
		public const long PDH_INVALID_DATA = 0xc0000bc6L;
		public const long PDH_INVALID_DATASOURCE = 0xc0000bddL;
		public const long PDH_INVALID_HANDLE = 0xc0000bbcL;
		public const long PDH_INVALID_INSTANCE = 0xc0000bc5L;
		public const long PDH_INVALID_PATH = 0xc0000bc4L;
		public const long PDH_INVALID_SQL_LOG_FORMAT = 0xc0000bf5L;
		public const long PDH_INVALID_SQLDB = 0xc0000bdeL;
		public const long PDH_LOG_FILE_CREATE_ERROR = 0xc0000bc9L;
		public const long PDH_LOG_FILE_OPEN_ERROR = 0xc0000bcaL;
		public const long PDH_LOG_FILE_TOO_SMALL = 0xc0000bdcL;
		public const long PDH_LOG_SAMPLE_TOO_SMALL = 0xc0000bf8L;
		public const long PDH_LOG_TYPE_NOT_FOUND = 0xc0000bcbL;
		public const long PDH_LOGSVC_NOT_OPENED = 0xc0000bd9L;
		public const long PDH_LOGSVC_QUERY_NOT_FOUND = 0xc0000bd8L;
		public const long PDH_MEMORY_ALLOCATION_FAILURE = 0xc0000bbbL;
		public const long PDH_MORE_DATA = 0x800007d2L;
		public const long PDH_NO_COUNTERS = 0xc0000bdfL;
		public const long PDH_NO_DATA = 0x800007d5L;
		public const long PDH_NO_DIALOG_DATA = 0xc0000bc7L;
		public const long PDH_NO_MORE_DATA = 0xc0000bccL;
		public const long PDH_NOT_IMPLEMENTED = 0xc0000bd3L;
		public const long PDH_OS_EARLIER_VERSION = 0xc0000bfaL;
		public const long PDH_OS_LATER_VERSION = 0xc0000bf9L;
		public const long PDH_PLA_COLLECTION_ALREADY_RUNNING = 0xc0000be9L;
		public const long PDH_PLA_COLLECTION_NOT_FOUND = 0xc0000bebL;
		public const long PDH_PLA_ERROR_ALREADY_EXISTS = 0xc0000beeL;
		public const long PDH_PLA_ERROR_FILEPATH = 0xc0000bf0L;
		public const long PDH_PLA_ERROR_NAME_TOO_LONG = 0xc0000bf4L;
		public const long PDH_PLA_ERROR_NOSTART = 0xc0000bedL;
		public const long PDH_PLA_ERROR_SCHEDULE_ELAPSED = 0xc0000becL;
		public const long PDH_PLA_ERROR_SCHEDULE_OVERLAP = 0xc0000beaL;
		public const long PDH_PLA_ERROR_TYPE_MISMATCH = 0xc0000befL;
		public const long PDH_PLA_SERVICE_ERROR = 0xc0000bf1L;
		public const long PDH_PLA_VALIDATION_ERROR = 0xc0000bf2L;
		public const long PDH_PLA_VALIDATION_WARNING = 0x80000bf3L;
		public const long PDH_QUERY_PERF_DATA_TIMEOUT = 0xc0000bfeL;
		public const long PDH_RETRY = 0x800007d4L;
		public const long PDH_SQL_ALLOC_FAILED = 0xc0000be0L;
		public const long PDH_SQL_ALLOCCON_FAILED = 0xc0000be1L;
		public const long PDH_SQL_ALTER_DETAIL_FAILED = 0xc0000bfdL;
		public const long PDH_SQL_BIND_FAILED = 0xc0000be7L;
		public const long PDH_SQL_CONNECT_FAILED = 0xc0000be6L;
		public const long PDH_SQL_EXEC_DIRECT_FAILED = 0xc0000be2L;
		public const long PDH_SQL_FETCH_FAILED = 0xc0000be3L;
		public const long PDH_SQL_MORE_RESULTS_FAILED = 0xc0000be5L;
		public const long PDH_SQL_ROWCOUNT_FAILED = 0xc0000be4L;
		public const long PDH_STRING_NOT_FOUND = 0xc0000bd4L;
		public const long PDH_UNABLE_MAP_NAME_FILES = 0x80000bd5L;
		public const long PDH_UNABLE_READ_LOG_HEADER = 0xc0000bd0L;
		public const long PDH_UNKNOWN_LOG_FORMAT = 0xc0000bd6L;
		public const long PDH_UNKNOWN_LOGSVC_COMMAND = 0xc0000bd7L;
		public const long PDH_UNMATCHED_APPEND_COUNTER = 0xc0000bfcL;
		public const long PDH_WBEM_ERROR = 0xc0000bdaL;
	}
}